const allQuestionList=[
    {
      "questionName": "Two Sum",
      "idNo": "001",
      "urlLink": "https://leetcode.com/problems/two-sum/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "Best Time to Buy and Sell Stock",
      "idNo": "002",
      "urlLink": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "Remove Duplicates from Sorted Array",
      "idNo": "003",
      "urlLink": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "Contains Duplicate",
      "idNo": "004",
      "urlLink": "https://leetcode.com/problems/contains-duplicate/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "Maximum Subarray",
      "idNo": "005",
      "urlLink": "https://leetcode.com/problems/maximum-subarray/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "Move Zeroes",
      "idNo": "006",
      "urlLink": "https://leetcode.com/problems/move-zeroes/",
      "topic": "Array",
      "level": "easy",
    },
    {
      "questionName": "3Sum",
      "idNo": "007",
      "urlLink": "https://leetcode.com/problems/3sum/",
      "topic": "Array",
      "level": "medium",
    },
    {
      "questionName": "Product of Array Except Self",
      "idNo": "008",
      "urlLink": "https://leetcode.com/problems/product-of-array-except-self/",
      "topic": "Array",
      "level": "medium",
    },
    {
      "questionName": "Subarray Sum Equals K",
      "idNo": "009",
      "urlLink": "https://leetcode.com/problems/subarray-sum-equals-k/",
      "topic": "Array",
      "level": "medium",
    },
    {
      "questionName": "Find Minimum in Rotated Sorted Array",
      "idNo": "010",
      "urlLink": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
      "topic": "Array",
      "level": "medium",
    },
    {
      "questionName": "Longest Consecutive Sequence",
      "idNo": "011",
      "urlLink": "https://leetcode.com/problems/longest-consecutive-sequence/",
      "topic": "Array",
      "level": "medium",
    },
    {
      "questionName": "Trapping Rain Water",
      "idNo": "012",
      "urlLink": "https://leetcode.com/problems/trapping-rain-water/",
      "topic": "Array",
      "level": "hard",
    },
    {
      "questionName": "Merge k Sorted Lists",
      "idNo": "013",
      "urlLink": "https://leetcode.com/problems/merge-k-sorted-lists/",
      "topic": "Array",
      "level": "hard",
    },
    {
      "questionName": "Sliding Window Maximum",
      "idNo": "014",
      "urlLink": "https://leetcode.com/problems/sliding-window-maximum/",
      "topic": "Array",
      "level": "hard",
    },
    {
      "questionName": "Median of Two Sorted Arrays",
      "idNo": "015",
      "urlLink": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
      "topic": "Array",
      "level": "hard",
    },

    // 2D array ...
    {
        "questionName": "Flood Fill",
        "idNo": "016",
        "urlLink": "https://leetcode.com/problems/flood-fill/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Matrix Diagonal Sum",
        "idNo": "017",
        "urlLink": "https://leetcode.com/problems/matrix-diagonal-sum/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Toeplitz Matrix",
        "idNo": "018",
        "urlLink": "https://leetcode.com/problems/toeplitz-matrix/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Matrix Reshape",
        "idNo": "019",
        "urlLink": "https://leetcode.com/problems/reshape-the-matrix/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Island Perimeter",
        "idNo": "020",
        "urlLink": "https://leetcode.com/problems/island-perimeter/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Check if Every Row and Column Contains All Numbers",
        "idNo": "021",
        "urlLink": "https://leetcode.com/problems/check-if-every-row-and-column-contains-all-numbers/",
        "topic": "2D Array",
        "level": "easy",
      },
      {
        "questionName": "Set Matrix Zeroes",
        "idNo": "022",
        "urlLink": "https://leetcode.com/problems/set-matrix-zeroes/",
        "topic": "2D Array",
        "level": "medium",
      },
      {
        "questionName": "Spiral Matrix",
        "idNo": "023",
        "urlLink": "https://leetcode.com/problems/spiral-matrix/",
        "topic": "2D Array",
        "level": "medium",
      },
      {
        "questionName": "Search a 2D Matrix",
        "idNo": "024",
        "urlLink": "https://leetcode.com/problems/search-a-2d-matrix/",
        "topic": "2D Array",
        "level": "medium",
      },
      {
        "questionName": "Diagonal Traverse",
        "idNo": "025",
        "urlLink": "https://leetcode.com/problems/diagonal-traverse/",
        "topic": "2D Array",
        "level": "medium",
      },
      {
        "questionName": "Kth Smallest Element in a Sorted Matrix",
        "idNo": "026",
        "urlLink": "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        "topic": "2D Array",
        "level": "medium",
      },
      {
        "questionName": "Maximal Rectangle",
        "idNo": "027",
        "urlLink": "https://leetcode.com/problems/maximal-rectangle/",
        "topic": "2D Array",
        "level": "hard",
      },
      {
        "questionName": "Word Search II",
        "idNo": "028",
        "urlLink": "https://leetcode.com/problems/word-search-ii/",
        "topic": "2D Array",
        "level": "hard",
      },
      {
        "questionName": "Max Sum of Rectangle No Larger Than K",
        "idNo": "029",
        "urlLink": "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/",
        "topic": "2D Array",
        "level": "hard",
      },
      {
        "questionName": "Longest Increasing Path in a Matrix",
        "idNo": "030",
        "urlLink": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        "topic": "2D Array",
        "level": "hard",
      }
]
  

module.exports=allQuestionList;